require("./lib/resource")
require("./lib/disaster")

Resource.create({name: "Can of Beans", cost: 1.29, incrementable: true, unit: "Can", item_type: "Food", value: 4, blurb: "Protein rich, cheap and long storage life."})
Resource.create({name: "Bottled Water", cost: 15.00, incrementable: true, unit: "Gallon", item_type: "Water", value: 2, blurb: "16oz of fresh water."})
Resource.create({name: "Black Cherry Fresca", cost: 1.79, incrementable: true, unit: "Can", item_type: "Water", value: 1, blurb: "Delicious zero calorie soft drink."})
Resource.create({name: "Pabst Blue Ribbon Six Pack", cost: 5.79, incrementable: true, unit: "Can", item_type: "Water", value: 4, blurb: "Delicious beverage. Not the best at hydrating though."})
Resource.create({name: "Vicodin", cost: 5.00, incrementable: true, unit: "Pill", item_type: "Medicine", value: 3, blurb: "It takes the pain away."})
Resource.create({name: "Jar of Pickles", cost: 3.59, incrementable: true, unit: "Jar", item_type: "Food", value: 1, blurb: "Preserved cucumbers. Stores well, but not many nutrients."})
Resource.create({name: "Hard Hat", cost: 20.00, incrementable: false, unit: "Special", item_type: "Special", value: 3, blurb: "Keeps you afloat in case of tidal wave, bridge collapse or other hazards."})
Resource.create({name: "Rubber Gloves", cost: 2.59, incrementable: true, unit: "Pair", item_type: "Special", value: 3, blurb: "If disease strikes, these will help you avoid catching it."})
Resource.create({name: "Can of Chicken Soup", cost: 2.29, incrementable: true, unit: "Can", item_type: "Food", value: 2, blurb: "Contains valuable protein and carbs. Best Served hot."})
Resource.create({name: "MRE", cost: 4.29, incrementable: true, unit: "Package", item_type: "Food", value: 12, blurb: "High density military ration. About 1200 calories."})
Resource.create({name: "Dried Apples", cost: 4.19, incrementable: true, unit: "Package", item_type: "Food", value: 4, blurb: "4.5oz package."})
Resource.create({name: "Gallon Jug of Water", cost: 5.79, incrementable: true, unit: "Package", item_type: "Water", value: 8, blurb: "Humans require about one gallon of water a day."})
Resource.create({name: "10 lb Bag of Rice", cost: 14.99, incrementable: true, unit: "Package", item_type: "Food", value: 120, blurb: "Dry white rice. Cheap, calorically dense."})
Resource.create({name: "Can of Tuna", cost: 0.99, incrementable: true, unit: "Can", item_type: "Food", value: 2, blurb: "Cooked, canned protein. Good on salad or in a sandwich."})
Resource.create({name: "Gas Mask", cost: 148.99, incrementable: false, unit: "Mask", item_type: "Special", value: 2, blurb: "Tactical gas mask. Protects you from inhaling toxic materials."})
Resource.create({name: "Hazmat Suit", cost: 178.99, incrementable: false, unit: "Suit", item_type: "Special", value: 2, blurb: "Full body cover to protect from biohazard and disease."})
Resource.create({name: "Cat Food", cost: 0.59, incrementable: true, unit: "Can", item_type: "Food", value: 1, blurb: "Meow meow meow meow meow meow meow meow."})


Disaster.create({name: 'Earthquake'})
Disaster.create({name: 'Contagion'})
Disaster.create({name: 'Nuclear'})
